version: '3.8'

services:
  # API Gateway - Punto de entrada principal
  api-gateway:
    build: ./micro-servicios/api-gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
      - ./micro-servicios/api-gateway/.env
    depends_on:
      - user-service
      - products-service
      - buy-service
      - court-service
      - match-service
      - cloudinary-service
    networks:
      - osc-network
    restart: unless-stopped

  # User Service
  user-service:
    build: ./micro-servicios/user-service
    ports:
      - "3001:3001"
    env_file:
      - .env
      - ./micro-servicios/user-service/.env
    networks:
      - osc-network
    restart: unless-stopped

  # Products Service
  products-service:
    build: ./micro-servicios/products-service
    ports:
      - "3002:3002"
    env_file:
      - .env
      - ./micro-servicios/products-service/.env
    networks:
      - osc-network
    restart: unless-stopped

  # Buy Service
  buy-service:
    build: ./micro-servicios/buy-service
    ports:
      - "3003:3003"
    env_file:
      - .env
      - ./micro-servicios/buy-service/.env
    networks:
      - osc-network
    restart: unless-stopped

  # Court Service
  court-service:
    build: ./micro-servicios/court-service
    ports:
      - "3004:3004"
    env_file:
      - .env
      - ./micro-servicios/court-service/.env
    networks:
      - osc-network
    restart: unless-stopped

  # Match Service
  match-service:
    build: ./micro-servicios/match-service
    ports:
      - "3005:3005"
    env_file:
      - .env
      - ./micro-servicios/match-service/.env
    networks:
      - osc-network
    restart: unless-stopped

  # Cloudinary Service
  cloudinary-service:
    build: ./micro-servicios/cloudinary-service
    ports:
      - "3006:3006"
    env_file:
      - .env
      - ./micro-servicios/cloudinary-service/.env
    networks:
      - osc-network
    restart: unless-stopped

networks:
  osc-network:
    driver: bridge

# Volúmenes opcionales para persistencia de datos (si es necesario)
# volumes:
#   db-data: